# Generated by Django 3.2.23 on 2024-02-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='highlight',
        ),
    ]
