# Generated by Django 3.2.23 on 2024-02-13 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('family-and-friends', 'Family and Friends'), ('pets-and-animals', 'Pets and Animals'), ('relationships', 'Relationships'), ('health-and-fitness', 'Health and Fitness'), ('food-and-drink', 'Food and Drink'), ('self-care', 'Self-Care'), ('creativity', 'Creativity'), ('entertainment-and-music', 'Entertainment and Music'), ('travel-and-adventure', 'Travel and Adventure'), ('work-and-education', 'Work and Education'), ('funny', 'Funny'), ('other', 'Other')], default='family-and-friends', max_length=250)),
                ('image', models.ImageField(blank=True, default='../default_image_rfyixk', upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tagged_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
