# Generated by Django 3.2.23 on 2024-02-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0006_highlight_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
