# Generated by Django 3.2.23 on 2024-02-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0007_alter_highlight_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
