# Generated by Django 3.2.23 on 2024-02-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0008_alter_highlight_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='updated_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
