# Generated by Django 3.2.23 on 2024-02-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0009_alter_highlight_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='image',
            field=models.ImageField(blank=True, default='../default_image_rfyixk', null=True, upload_to='images/'),
        ),
    ]
