# Generated by Django 3.2.23 on 2024-02-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0011_alter_highlight_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='image',
            field=models.ImageField(blank=True, default='../default_image_rfyixk', null=True, upload_to='images/'),
        ),
    ]
