# Generated by Django 3.2.23 on 2024-02-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0014_alter_highlight_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
