# Generated by Django 3.2.23 on 2024-03-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0016_alter_highlight_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='improve',
            field=models.TextField(blank=True),
        ),
    ]
