# Generated by Django 3.2.23 on 2024-03-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20240312_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='lname',
            new_name='last_name',
        ),
    ]
